services:
  db_critik:
    image: postgres:latest
    container_name: db_critik

    env_file: ./server/.env
    ports:
      - "5432:5432"
    # networks:
    #   - critik_network
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "pg_isready -U admin -d DB -h localhost -p 5432 -t 5 -q 1>/dev/null 2>&1 || exit 1",
    #     ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 0
    volumes:
      - db_critik_data:/var/lib/postgresql/data

  # creation of backend
  # backend_critik:
  #   build:
  #     context: ./server
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     db_critik:
  #       condition: service_healthy
  #   networks:
  #     - critik_network

# networking configuration
# networks:
#   critik_network:
#     driver: bridge
volumes:
  db_critik_data:
    driver: local
  resumes_images:
    driver: local
