name: Build Docker image and push on github registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        working-directory: ./server
        run: pnpm install --frozen-lockfile

      - name: Copy .env.example to .env and modify variables
        shell: bash
        run: cp ./server/.env.example ./server/.env

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Connect to Server and Execute Commands
        env:
          SSH_USERNAME: root
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        shell: bash
        run: |
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST
          cd /
          git clone https://github.com/${{ github.repository }}

          
