name: Push to remote server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 21
      # - name: Install pnpm
      #   run: npm install -g pnpm
      # - name: Install dependencies
      #   working-directory: ./server
      #   run: pnpm install --frozen-lockfile

      # - name: Copy .env.example to .env and modify variables
      #   shell: bash
      #   run: cp ./server/.env.example ./server/.env

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
             whoami
             cd /critik-v
             git clone ${{github.repositoryUrl}}


          
