name: Build Docker image and push on github registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Copy .env.example to .env and modify variables
        env:
          NODE_ENV: production
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          DB_SERVICE: ${{ secrets.DB_SERVICE }}
          API_NAME: ${{ secrets.API_NAME }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          CLIENT_SERVICE: ${{ secrets.CLIENT_SERVICE }}
          CLIENT_PORT: ${{ secrets.CLIENT_PORT }}
          PDF_CONVERTER_SERVICE: ${{ secrets.PDF_CONVERTER_SERVICE }}
          PDF_CONVERTER_PORT: ${{ secrets.PDF_CONVERTER_PORT }}
        run: |
          cp ./server/.env.example ./server/.env
          sed -i "s/NODE_ENV=.*$/NODE_ENV=$NODE_ENV/" ./server/.env
          sed -i "s/SERVER_PORT=.*$/SERVER_PORT=$SERVER_PORT/" ./server/.env
          sed -i "s/DB_SERVICE=.*$/DB_SERVICE=$DB_SERVICE/" ./server/.env
          sed -i "s/API_NAME=.*$/API_NAME=$API_NAME/" ./server/.env
          sed -i "s/GOOGLE_CLIENT_ID=.*$/GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID/" ./server/.env
          sed -i "s/GOOGLE_CLIENT_SECRET=.*$/GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET/" ./server/.env
          sed -i "s/GOOGLE_REDIRECT_URI=.*$/GOOGLE_REDIRECT_URI=$GOOGLE_REDIRECT_URI/" ./server/.env
          sed -i "s/SESSION_SECRET=.*$/SESSION_SECRET=$SESSION_SECRET/" ./server/.env
          sed -i "s/CLIENT_SERVICE=.*$/CLIENT_SERVICE=$CLIENT_SERVICE/" ./server/.env
          sed -i "s/CLIENT_PORT=.*$/CLIENT_PORT=$CLIENT_PORT/" ./server/.env
          sed -i "s/PDF_CONVERTER_SERVICE=.*$/PDF_CONVERTER_SERVICE=$PDF_CONVERTER_SERVICE/" ./server/.env
          sed -i "s/PDF_CONVERTER_PORT=.*$/PDF_CONVERTER_PORT=$PDF_CONVERTER_PORT/" ./server/.env
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push
        run: |
          docker build . --file /server/Dockerfile --tag ${{ github.repository }}:latest
          docker push ${{ github.repository }}:latest
