name: lint the project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'
      - name: Install dependencies
        run: |
          npm install -g pnpm
          cd ./server
          pnpm install --frozen-lockfile
      - name: Run eslint
        run: pnpm eslint . --ext .js,.ts
