name: lint the project

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install eslint
        run: npm install -g eslint@8.56.0
      - name: install dependencies
        working-directory: ./server
        run: pnpm install --frozen-lockfile
      - name: Run eslint
        working-directory: ./server
        shell: bash
        run: pnpm run lint
