name: lint the project

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: npm install -g pnpm
      - run: pnpm install -g eslint
      - run: pnpx eslint --ext .tsx .
